const CircularDependencyPlugin = require('circular-dependency-plugin')

module.exports = {

	entry: './src/index.ts',
	output: {
		filename: 'emu-hub.js'
	},
	resolve: {
		extensions: ['.ts', '.js', '']
	},
	module: {
		loaders: [
			{
				test: /\.ts?$/,
				loader: 'ts-loader',
				exclude: /node_modules/
			}
		]
	},
	plugins: [
		new CircularDependencyPlugin({
			// exclude detection of files based on a RegExp
			exclude: /a\.js|node_modules/,
			// add errors to webpack instead of warnings
			failOnError: true,
			// `onDetected` is called for each module that is cyclical
			onDetected({ module: webpackModuleRecord, paths, compilation }) {
				// `paths` will be an Array of the relative module paths that make up the cycle
				// `module` will be the module record generated by webpack that caused the cycle
				compilation.errors.push(new Error(paths.join(' -> ')))
			}
		})
	]

};